// src/data/events.ts
import type { Event, ISODateString } from "@/types/event";

export const EVENTS: Event[] = [
  {
    id: "evt_ai_001",
    slug: "techthyme-building-a-future-with-ai",
    title: "TechThyme: Building a Future with AI",
    coverImage:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1200&auto=format&fit=crop",
    dateStart: "2025-10-05T18:00:00Z" as ISODateString,
    dateEnd: "2025-10-05T21:00:00Z" as ISODateString,
    timezone: "America/St_Thomas",
    venue: {
      kind: "in_person",
      name: "UVI Innovation Lab",
      city: "St. Thomas",
      region: "VI",
      country: "US",
      lat: 18.3358,
      lng: -64.8963,
      mapUrl: "https://maps.example/uvi-innovation-lab",
    },
    locationText: "St. Thomas, USVI — UVI Innovation Lab",
    summary:
      "Hands-on workshop series on computer science, software engineering, and AI.",
    description:
      "Dive into JSON, APIs, data structures, and build your first AI-powered web app with guidance from TechThyme mentors.",
    organizer: { name: "TechThyme", url: "https://techthyme.vi" },
    capacity: 120,
    attendingCount: 86,
    status: "scheduled",
    priceUSD: 0,
    categories: ["Education", "Workshop"],
    tags: ["AI", "Education", "Workshop"],
    tickets: [
      { id: "t_ai_ga", name: "General Admission", priceUSD: 0, perOrderLimit: 4 },
    ],
    published: true,
    createdAt: "2025-09-01T12:00:00Z" as ISODateString,
    updatedAt: "2025-09-18T10:00:00Z" as ISODateString,
  },
  {
    id: "evt_comm_002",
    slug: "farmers-market-harvest-fest",
    title: "Farmers’ Market Harvest Fest",
    coverImage: {
      url: "https://images.unsplash.com/photo-1506806732259-39c2d0268443?q=80&w=1200&auto=format&fit=crop",
      alt: "Fresh produce at an outdoor market",
      width: 1200,
      height: 800,
    },
    dateStart: "2025-11-02T14:00:00Z" as ISODateString,
    dateEnd: "2025-11-02T20:00:00Z" as ISODateString,
    timezone: "America/St_Thomas",
    venue: {
      kind: "in_person",
      name: "Emancipation Garden",
      city: "Charlotte Amalie",
      region: "VI",
      country: "US",
    },
    locationText: "Emancipation Garden, Charlotte Amalie, St. Thomas",
    summary: "Live music, local produce, cooking demos, and kids’ activities.",
    description:
      "Celebrate the harvest with local farmers and artisans. Taste, learn, and support the community.",
    organizer: { name: "Cultiv8VI" },
    capacity: 500,
    attendingCount: 410,
    status: "scheduled",
    priceUSD: 5,
    categories: ["Community"],
    tags: ["Food", "Local", "Family"],
    tickets: [
      {
        id: "t_harvest_ga",
        name: "General Admission",
        priceUSD: 5,
        perOrderLimit: 10,
      },
      {
        id: "t_harvest_vip",
        name: "VIP Tasting",
        priceUSD: 25,
        capacity: 50,
        perOrderLimit: 2,
        description: "Includes tasting flight and chef Q&A.",
      },
    ],
    published: true,
    createdAt: "2025-09-10T09:00:00Z" as ISODateString,
    updatedAt: "2025-09-20T16:00:00Z" as ISODateString,
  },
  {
    id: "evt_online_003",
    slug: "intro-to-nextjs-app-router",
    title: "Intro to Next.js App Router",
    coverImage:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop",
    dateStart: "2025-10-15T22:00:00Z" as ISODateString,
    timezone: "America/New_York",
    venue: {
      kind: "online",
      platform: "Zoom",
      url: "https://zoom.example/next-app-router",
      meetingCode: "123-456-789",
    },
    locationText: "Online (Zoom)",
    summary: "A beginner-friendly walkthrough of routes, layouts, and data.",
    description:
      "Learn the fundamentals of Next.js App Router, including server components, caching, and API routes.",
    organizer: { name: "TechThyme" },
    capacity: 300,
    attendingCount: 300,
    status: "sold_out",
    priceUSD: 0,
    categories: ["Education", "Workshop"],
    tags: ["Next.js", "Web Dev"],
    tickets: [
      {
        id: "t_next_ga",
        name: "General Admission",
        priceUSD: 0,
        capacity: 300,
        perOrderLimit: 1,
      },
    ],
    published: true,
    createdAt: "2025-09-05T14:00:00Z" as ISODateString,
    updatedAt: "2025-09-19T11:30:00Z" as ISODateString,
  },
  {
    id: "evt_music_004",
    slug: "sunset-reggae-on-the-bay",
    title: "Sunset Reggae on the Bay",
    coverImage:
      "https://images.unsplash.com/photo-1487180144351-b8472da7d491?q=80&w=1200&auto=format&fit=crop",
    dateStart: "2025-12-20T23:30:00Z" as ISODateString,
    dateEnd: "2025-12-21T02:30:00Z" as ISODateString,
    timezone: "America/St_Thomas",
    venue: {
      kind: "in_person",
      name: "Waterfront Stage",
      city: "Red Hook",
      region: "VI",
      country: "US",
    },
    locationText: "Waterfront Stage, Red Hook, St. Thomas",
    summary: "Live reggae bands as the sun sets over the bay.",
    description:
      "Bring a chair, relax, and enjoy sweet rhythms with food trucks and local vendors.",
    organizer: { name: "Island Vibes Collective" },
    capacity: 800,
    attendingCount: 520,
    status: "scheduled",
    priceUSD: 15,
    categories: ["Music", "Community"],
    tags: ["Music", "Outdoor"],
    tickets: [
      { id: "t_reggae_ga", name: "General Admission", priceUSD: 15 },
      { id: "t_reggae_vip", name: "VIP Deck", priceUSD: 50, capacity: 100 },
    ],
    published: true,
    createdAt: "2025-09-07T08:00:00Z" as ISODateString,
    updatedAt: "2025-09-21T15:45:00Z" as ISODateString,
  },
  {
    id: "evt_conf_005",
    slug: "caribbean-tech-summit-2026",
    title: "Caribbean Tech Summit 2026",
    coverImage:
      "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?q=80&w=1200&auto=format&fit=crop",
    dateStart: "2026-02-10T13:00:00Z" as ISODateString,
    dateEnd: "2026-02-12T21:00:00Z" as ISODateString,
    timezone: "America/Puerto_Rico",
    venue: {
      kind: "in_person",
      name: "San Juan Convention Center",
      city: "San Juan",
      region: "PR",
      country: "US",
    },
    locationText: "San Juan Convention Center, Puerto Rico",
    summary: "Three days of talks, workshops, and networking.",
    description:
      "From AI to climate tech, meet founders, developers, and investors shaping the Caribbean tech ecosystem.",
    organizer: { name: "CaribTech Org", url: "https://carib.tech" },
    capacity: 3000,
    attendingCount: 0,
    status: "scheduled",
    priceUSD: 199,
    categories: ["Conference"],
    tags: ["AI", "Startups", "Networking"],
    tickets: [
      {
        id: "t_cts_early",
        name: "Early Bird",
        priceUSD: 149,
        capacity: 500,
        salesStart: "2025-10-01T04:00:00Z" as ISODateString,
        salesEnd: "2025-11-15T04:00:00Z" as ISODateString,
      },
      { id: "t_cts_std", name: "Standard", priceUSD: 199 },
      { id: "t_cts_vip", name: "VIP", priceUSD: 499, capacity: 150 },
    ],
    published: false, // draft
    createdAt: "2025-09-12T10:00:00Z" as ISODateString,
    updatedAt: "2025-09-20T10:00:00Z" as ISODateString,
  },
  {
    id: "evt_sports_006",
    slug: "softball-community-showcase",
    title: "Softball Community Showcase",
    coverImage:
      "https://images.unsplash.com/photo-1502810190503-8303352d0dd1?q=80&w=1200&auto=format&fit=crop",
    dateStart: "2025-10-26T17:00:00Z" as ISODateString,
    dateEnd: "2025-10-26T22:00:00Z" as ISODateString,
    timezone: "America/St_Thomas",
    venue: {
      kind: "in_person",
      name: "Lionel Roberts Stadium",
      city: "St. Thomas",
      region: "VI",
      country: "US",
    },
    locationText: "Lionel Roberts Stadium, St. Thomas",
    summary: "Exhibition games, skills clinics, and sign-ups.",
    description:
      "Meet coaches, try skills stations, and register for the upcoming league season.",
    organizer: { name: "USVI Softball Assoc." },
    capacity: 600,
    attendingCount: 120,
    status: "scheduled",
    priceUSD: 0,
    categories: ["Sports", "Community"],
    tags: ["Softball", "Youth", "Family"],
    tickets: [{ id: "t_softball_free", name: "Free RSVP", priceUSD: 0 }],
    published: true,
    createdAt: "2025-09-18T12:30:00Z" as ISODateString,
    updatedAt: "2025-09-21T12:00:00Z" as ISODateString,
  },
];

// (Optional) quick lookup by id
export const EVENTS_BY_ID = Object.fromEntries(EVENTS.map((e) => [e.id, e]));
